language: node_js

node_js:
  - 10.16.3

cache: npm

install:
  - npm ci
  - npm run build

deploy:
  provider: heroku
  api_key: 
    secure: 0c483dca-d763-40d8-ab45-65c81f8b1cd2
  run:
    npm run ssr
