language: node_js

node_js:
  - 10.16.3

cache: npm

install:
  - npm ci
  - npm run build

deploy:
  provider: heroku
  api_key: 
    secure: 4da32a49-413f-4929-a5df-54ba6f05b91f
  run:
    npm run ssr
