language: node_js

node_js:
  - 10.16.3

cache: npm

install:
  - npm ci
  - npm run build

deploy:
  provider: heroku
  api_key: d3e90a84-ca42-478e-9b44-7cb63887312a
  app: gj-hacker-news
  run:
    npm run ssr
